### ISSUE TITLE
Colour Scheme

### ISSUE THREAD

**Issue by ZichengLiang** [ZichengLiang/CSU11013-GroupB-Team9#44]
@Pikacrazy Hi Muireann, we can work a little on a better colour scheme of our progam.
here are some reference websites:
1. https://colorlisa.com/ it provides the colour in famous artists' works
2. https://nipponcolors.com/ it offers the traditional Japanese palette

**Comment by Pikacrazy** [comment]
Certainly! I'll take a look 👍

**Comment by Pikacrazy** [comment]
I was thinking a little bit about that over the weekend, it might be nice
to have the sidebar in a neutral tone- beige/gray or shades such as
black/white
Because those colors will go with most other colors available, and are most
likely to match the colored tone for the main screen

Aside from that we need to decide whether we want warm or cool colours

Eg, whether we want our program to be
Lively and exiting, warm
Or
Calm and relaxing, cool

**Comment by Pikacrazy** [comment]
I really enjoyed the color pages you chose. We could definitely use one of
those palettes
